var searchData=
[
  ['c_20c_20projects_0',['Running a Makefile for C/C++ Projects',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['c_20is_20a_20class_20that_20contains_20at_20least_20one_20pure_20virtual_20function_20a_20pure_20virtual_20function_20is_20a_20virtual_20function_20for_20which_20we_20provide_20only_20the_20declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_1',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_2',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['characteristics_20of_20an_20abstract_20class_20are_3a_3',['The key characteristics of an abstract class are:',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['class_20are_3a_4',['The key characteristics of an abstract class are:',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['class_20in_20c_20is_20a_20class_20that_20contains_20at_20least_20one_20pure_20virtual_20function_20a_20pure_20virtual_20function_20is_20a_20virtual_20function_20for_20which_20we_20provide_20only_20the_20declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_5',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['class_20zmogus_6',['Abstract Class &quot;Zmogus&quot;',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['classes_7',['Structures vs Classes',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_8',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['code_9',['1\. Write Your Code',['../md__r_e_a_d_m_e.html#autotoc_md27',1,'']]],
  ['code_20with_20flags_10',['6\. How To Run Code With Flags',['../md__r_e_a_d_m_e.html#autotoc_md33',1,'']]],
  ['command_20prompt_11',['3\. Open Terminal/Command Prompt',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'']]],
  ['common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_12',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['constructor_13',['Constructor',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'Copy Constructor'],['../md__r_e_a_d_m_e.html#autotoc_md15',1,'Move Constructor']]],
  ['constructs_20a_20tt_20studentas_20tt_20object_20accordingly_14',['The input operator &lt;tt&gt;operator\&gt;\&gt;&lt;/tt&gt; is overloaded to deserialize a &lt;tt&gt;Studentas&lt;/tt&gt; object from an input stream. It reads &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; from the input stream and constructs a &lt;tt&gt;Studentas&lt;/tt&gt; object accordingly.',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['contains_20at_20least_20one_20pure_20virtual_20function_20a_20pure_20virtual_20function_20is_20a_20virtual_20function_20for_20which_20we_20provide_20only_20the_20declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_15',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['copy_20assignment_20operator_16',['Copy Assignment Operator',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['copy_20constructor_17',['Copy Constructor',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['copy_20of_20an_20existing_20object_18',['Creates a new object as a copy of an existing object.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['creates_20a_20new_20object_20as_20a_20copy_20of_20an_20existing_20object_19',['Creates a new object as a copy of an existing object.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]]
];
