var searchData=
[
  ['serialize_20a_20tt_20studentas_20tt_20object_20to_20an_20output_20stream_20it_20prints_20the_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20member_20variables_20to_20the_20output_20stream_0',['The output operator &lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; is overloaded to serialize a &lt;tt&gt;Studentas&lt;/tt&gt; object to an output stream. It prints the &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; member variables to the output stream.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_1',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['set_20of_20methods_20that_20derived_20classes_20must_20implement_2',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['specs_3',['Specs',['../md__r_e_a_d_m_e.html',1,'']]],
  ['state_20of_20one_20object_20to_20another_20existing_20object_4',['Assigns the state of one object to another existing object.',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['stream_20it_20prints_20the_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20member_20variables_20to_20the_20output_20stream_5',['The output operator &lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; is overloaded to serialize a &lt;tt&gt;Studentas&lt;/tt&gt; object to an output stream. It prints the &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; member variables to the output stream.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['stream_20it_20reads_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20from_20the_20input_20stream_20and_20constructs_20a_20tt_20studentas_20tt_20object_20accordingly_6',['The input operator &lt;tt&gt;operator\&gt;\&gt;&lt;/tt&gt; is overloaded to deserialize a &lt;tt&gt;Studentas&lt;/tt&gt; object from an input stream. It reads &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; from the input stream and constructs a &lt;tt&gt;Studentas&lt;/tt&gt; object accordingly.',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['structures_20vs_20classes_7',['Structures vs Classes',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['studentas_8',['Studentas',['../class_studentas.html',1,'']]],
  ['studentas_20tt_20object_20from_20an_20input_20stream_20it_20reads_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20from_20the_20input_20stream_20and_20constructs_20a_20tt_20studentas_20tt_20object_20accordingly_9',['The input operator &lt;tt&gt;operator\&gt;\&gt;&lt;/tt&gt; is overloaded to deserialize a &lt;tt&gt;Studentas&lt;/tt&gt; object from an input stream. It reads &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; from the input stream and constructs a &lt;tt&gt;Studentas&lt;/tt&gt; object accordingly.',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['studentas_20tt_20object_20to_20an_20output_20stream_20it_20prints_20the_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20member_20variables_20to_20the_20output_20stream_10',['The output operator &lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; is overloaded to serialize a &lt;tt&gt;Studentas&lt;/tt&gt; object to an output stream. It prints the &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; member variables to the output stream.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]]
];
