var searchData=
[
  ['pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20from_20the_20input_20stream_20and_20constructs_20a_20tt_20studentas_20tt_20object_20accordingly_0',['The input operator &lt;tt&gt;operator\&gt;\&gt;&lt;/tt&gt; is overloaded to deserialize a &lt;tt&gt;Studentas&lt;/tt&gt; object from an input stream. It reads &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; from the input stream and constructs a &lt;tt&gt;Studentas&lt;/tt&gt; object accordingly.',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20member_20variables_20to_20the_20output_20stream_1',['The output operator &lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; is overloaded to serialize a &lt;tt&gt;Studentas&lt;/tt&gt; object to an output stream. It prints the &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; member variables to the output stream.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['prerequisites_2',['Prerequisites',['../md__r_e_a_d_m_e.html#autotoc_md25',1,'']]],
  ['prints_20the_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20member_20variables_20to_20the_20output_20stream_3',['The output operator &lt;tt&gt;operator\&lt;\&lt;&lt;/tt&gt; is overloaded to serialize a &lt;tt&gt;Studentas&lt;/tt&gt; object to an output stream. It prints the &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; member variables to the output stream.',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['program_4',['6\. Run Your Program',['../md__r_e_a_d_m_e.html#autotoc_md32',1,'']]],
  ['project_20directory_5',['4\. Navigate to Project Directory',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['projects_6',['Running a Makefile for C/C++ Projects',['../md__r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['prompt_7',['3\. Open Terminal/Command Prompt',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'']]],
  ['provide_20only_20the_20declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_8',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_9',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['pure_20virtual_20function_20a_20pure_20virtual_20function_20is_20a_20virtual_20function_20for_20which_20we_20provide_20only_20the_20declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_10',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]]
];
