var searchData=
[
  ['declaration_20in_20the_20base_20class_20without_20providing_20any_20implementation_20abstract_20classes_20are_20designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_0',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_1',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['derived_20classes_20must_20implement_2',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['deserialize_20a_20tt_20studentas_20tt_20object_20from_20an_20input_20stream_20it_20reads_20tt_20vardas_20tt_20tt_20pavarde_20tt_20tt_20egzaminas_20tt_20and_20tt_20nd_5frezultatai_20tt_20from_20the_20input_20stream_20and_20constructs_20a_20tt_20studentas_20tt_20object_20accordingly_3',['The input operator &lt;tt&gt;operator\&gt;\&gt;&lt;/tt&gt; is overloaded to deserialize a &lt;tt&gt;Studentas&lt;/tt&gt; object from an input stream. It reads &lt;tt&gt;vardas&lt;/tt&gt;, &lt;tt&gt;pavarde&lt;/tt&gt;, &lt;tt&gt;egzaminas&lt;/tt&gt;, and &lt;tt&gt;nd_rezultatai&lt;/tt&gt; from the input stream and constructs a &lt;tt&gt;Studentas&lt;/tt&gt; object accordingly.',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'']]],
  ['designed_20to_20be_20used_20as_20base_20classes_20and_20they_20cannot_20be_20instantiated_20directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_4',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['destructor_5',['Destructor',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['directly_20instead_20they_20are_20intended_20to_20serve_20as_20interfaces_20that_20define_20a_20common_20set_20of_20methods_20that_20derived_20classes_20must_20implement_6',['An abstract class in C++ is a class that contains at least one pure virtual function. A pure virtual function is a virtual function for which we provide only the declaration in the base class, without providing any implementation. Abstract classes are designed to be used as base classes, and they cannot be instantiated directly. Instead, they are intended to serve as interfaces that define a common set of methods that derived classes must implement.',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['directory_7',['4\. Navigate to Project Directory',['../md__r_e_a_d_m_e.html#autotoc_md30',1,'']]]
];
